on: [push, pull_request]

name: cmake-python

jobs:
  test:
    name: Test ${{ matrix.os }} Python ${{ matrix.python }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2016"]
        python: ["2.7", "3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies 
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --disable-pip-version-check --upgrade pip
          pip install pytest-virtualenv -f https://github.com/jcfr/pytest-plugins/releases/tag/v1.7.0.dev15 --pre
          pip install git+https://github.com/jcfr/wheeltools.git@wheeltools-2018-10-28-a2f174d0e
          pip install -r requirements-dev.txt
      - name: Build CMake
        #  $<SETUP_BDIST_WHEEL_ARGS> -- $<SETUP_CMAKE_ARGS> -- $<SETUP_MAKE_ARGS>
        run: |
          flake8
          # Source distribution
          python setup.py --hide-listing sdist
          # Built distribution (wheel)
          python setup.py --hide-listing bdist_wheel
          # Cleanup
          echo "import glob, os
          if os.environ.get('UPLOAD_SDIST', '') == '':
              sdist=(glob.glob('dist/*.tar.gz') + glob.glob('dist/*.zip'))[0]
              print('Deleting [%s]' % sdist)
              os.remove(sdist)" | python
          # Convert to generic platform wheel
          echo "import glob, sys
          sys.path.insert(0, './scripts')
          from convert_to_generic_platform_wheel import convert_to_generic_platform_wheel
          wheels = glob.glob('dist/*.whl')
          for wheel in wheels:
              convert_to_generic_platform_wheel(wheel, remove_original=True)" | python
      - name: Execute tests
        run: | 
          python setup.py test
  
## TODO: Deploy
