on: [push, pull_request]

name: cmake-python

jobs:
  test:
    name: Test ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["windows-2019"]
        python: ["2.7", "3.7"]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: |
          python -m pip install scikit-ci scikit-ci-addons
          python -m ci_addons --install ../addons
      - name: Execute rolling-build
        if: matrix.os == 'windows-2019'
        run: ../addons/appveyor/rolling-build.ps1
        shell: powershell
      - name: Build CMake
        run: |
          python -m ci install
          python -m ci build
          python -m ci test
          python -m ci after_test
      - name: Execute enable-worker-remote-accesss
        if: matrix.os == 'windows-2019'
        run: ../addons/appveyor/enable-worker-remote-access.ps1 -check_for_block
        shell: powershell
  
## TODO: Deploy
